name: Update Wiki

on:
  repository_dispatch:
    types: [update_wiki]

jobs:
  update-wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update wiki content
      run: |
        echo "${{ github.event.client_payload.content }}" | base64 --decode > ${{ github.event.client_payload.path }}
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add ${{ github.event.client_payload.path }}
        git commit -m "Update ${{ github.event.client_payload.path }} via GitHub Actions"
        git push

    env:
      GITHUB_TOKEN: ${{ secrets.WIKI_TOKEN_GITHUB }}
